@UI_Server_HostAddress = http://localhost:5097

###homepage with popular games
GET http://localhost:5097/api/Home

###find games in search bar
GET http://localhost:5097/api/Games?namePart=hol

###go to details of game
GET http://localhost:5097/api/Games/7abe12fd-0e59-4903-9dbd-b1549981c4fb

###post review
POST http://localhost:5097/api/Reviews
Content-Type: application/json

{
  "Title": "over 200 hours of playtime. Still can't get enough!",
  "Content": "Team Cherry’s Hollow Knight is a masterclass in atmosphere and design. Its gorgeous art style, eerie soundtrack, and tight combat make the first journey through Hallownest unforgettable. What sets it apart, though, is its replay value—with multiple endings, hidden bosses, and countless charm combinations, every run feels unique. The Godhome DLC pushes this even further, offering some of the hardest challenges in the game through boss rushes and Pantheons. Players can easily spend dozens of hours here alone, striving to conquer every trial and perfect their skills. Whether you’re aiming for 112% completion, experimenting with new builds, or tackling Godhome’s brutal challenges, Hollow Knight always gives you a reason to come back.",
  "Rating": 4,
  "Username": "MiraPoes",
  "GameId": "0CE40283-77A6-4F9D-BEB8-C2FD68BBD3BB"
}

###get suggestions based on the games you rated/played
GET http://localhost:5097/api/Games/suggestions?username=RobbeVO

###register new user
POST http://localhost:5097/api/Accounts
Content-Type: application/json

{
  "Username": "MiraPoes",
  "Email": "mira.cradleberry@hotmail.com",
  "Password": "MiauwVrrr98b"
}

###login to account
POST http://localhost:5097/api/Accounts/login
Content-Type: application/json

{
  "Identifier": "van.osselaer.robbe@hotmail.com",
  "Password": "Robbe371!"
}

###logout
POST http://localhost:5097/api/Accounts/logout

###create new game as admin
POST http://localhost:5097/api/Games
Content-Type: application/json

{
  "Name": "Kirby and the Forgotten Land",
  "Description": "explore a mysterious new land alone or with a friend, discover new copy-abilities and fight against the most diverse beasts in Kirby and the Forgotten Land on the Nintendo Switch!",
  "ImageUrl": "https://www.nintendo.com/eu/media/images/10_share_images/games_15/nintendo_switch_4/H2x1_NSwitch_KirbyAndTheForgottenLand_onlylogo_enGB_image1600w.jpg"
}